// This file reads a list of polynomials and computes a Gröbner basis
// of the rational ideal generated by them using the F4 algorithm.
//
// If there is now finite Gröbner basis it will not halt.
#include <bits/stdc++.h>
#include <gmpxx.h>

#include "ncgb/F4.hpp"

using namespace std;
using namespace ncgb;

typedef mpq_class R;
typedef Poly<R> P;

int main() {

  size_t n;
  cin >> n;
  vector<P> G(n);
  for (size_t i = 0; i < n; ++i) {
    cin >> G[i];
  }

  F4Incremental<R> F4(G);

  vector<P> base = F4.fullBase();

  cout << base.size() << endl;
  for (auto f : base) {
    f.nice_print();
  }
}

