// This file reads a list of polynomials, a polynomial and a number k and tries
// to determine if the polynomial is in the modular arithmetic modulo 1e9+7 ideal
// generated by the list of polynomial using k steps of the F4 algorithm.
//
// This is the same that InIdeal_F4.cpp but for modular arithmetic.
#include <bits/stdc++.h>

#include "ncgb/F4.hpp"
#include "extras/ModularArithmetic.hpp"

using namespace std;
using namespace ncgb;

const size_t mod = 1e9 + 7;
typedef Mod<mod> Zp;

typedef Poly<Zp> P;

int main() {
  size_t n;
  cin >> n;
  vector<P> G(n);
  for (size_t i = 0; i < n; ++i) {
    cin >> G[i];
  }

  P f;
  P g0;
  cin >> f;
  size_t k;
  cin >> k;

  IdealMembershipStatus ims = inIdeal_F4(G, f, k);

  if (ims == InIdeal) {
    cout << "InIdeal\n";
  } else {
    cout << "NotInIdeal or Unknown\n";
  }

}

