name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run:
        make test

  test_InIdeal:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install pyahocorasick
        sudo apt install sagemath
        python3 -m pip install git+https://github.com/ClemensHofstadler/operator_gb.git
    - name: Run test
      run:
        make test_InIdeal
