name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  internal_tests:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgivaro-dev libflint-dev
    - name: Run test
      run:
        make internal_tests

  InIdeal_tests:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgivaro-dev libflint-dev sagemath
        python3 -m pip install pyahocorasick
        python3 -m pip install git+https://github.com/ClemensHofstadler/operator_gb.git
    - name: Run test
      run:
        make InIdeal_tests

  base_tests:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgivaro-dev libflint-dev sagemath
        python3 -m pip install pyahocorasick
        python3 -m pip install git+https://github.com/ClemensHofstadler/operator_gb.git
    - name: Run test
      run:
        make base_tests

  cofactor_tests:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgivaro-dev libflint-dev
    - name: Run test
      run:
        make cofactor_tests

  parallelism_tests:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgivaro-dev libflint-dev
    - name: Run test
      run:
        make parallelism_tests
